name: quart-netlify-preview
description: 'Deploy quarto preview to netlify'
inputs:
  NETLIFY_AUTH_TOKEN:
    description: 'Netlify auth token.'
    required: true
  NETLIFY_SITE_ID:
    description: 'Netlify site id.'
    required: true
  Path:
    description: 'Path to rendered site.'
    required: true
    default: '.'
  GITHUB_TOKEN:
    description: 'Github Token.'
outputs:
  preview-url:
    description: 'Preview url.'
    value: ${{ steps.deploy-preview.outputs.preview-url }}
runs:
  using: "composite"
  steps:
    - name: Install netlify cli
      run: npm install netlify-cli -g
      shell: bash

    - name: Get pull request id
      run: echo "pr_id=$(echo "${{ github.ref_name }}" | tr / -)" >> $GITHUB_ENV
      shell: bash

    - name: Deploy to netlify
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ inputs.NETLIFY_SITE_ID }}
      run: netlify deploy --alias ${{ env.pr_id }} --dir ${{ github.workspace }}/${{ inputs.path }}
      shell: bash

    - name: Add url comment
      if: ${{ github.event.pull_request.action == 'opened' }}
      uses: peter-evans/create-or-update-comment@v2
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        issue-number: ${{ github.event.pull_request.number }}
        body: |
          [Preview](https://${{ env.pr_id }}--mlr-org.netlify.app)

