name: quart-netlify-preview
description: 'Deploy quarto preview to netlify'
inputs:
  NETLIFY_AUTH_TOKEN:
    description: 'Netlify auth token.'
    required: true
  NETLIFY_SITE_ID:
    description: 'Netlify site id.'
    required: true
  Path:
    description: 'Path to rendered site.'
    required: true
    default: '.'
outputs:
  preview-url:
    description: 'Preview url.'
    value: ${{ steps.deploy-preview.outputs.preview-url }}
runs:
  using: "composite"
  steps:
    - run: npm install netlify-cli -g
      shell: bash

    - id: deploy-preview
      env:
        NETLIFY_AUTH_TOKEN: ${{ input.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ input.NETLIFY_SITE_ID }}
      run: netlify deploy --dir ${{ GITHUB_WORKSPACE }}/${{ inputs.path }}
      shell: bash
