name: quart-netlify-preview
description: 'Deploy quarto preview to netlify'
inputs:
  NETLIFY_AUTH_TOKEN:
    description: 'Netlify auth token.'
    required: true
  NETLIFY_SITE_ID:
    description: 'Netlify site id.'
    required: true
  Path:
    description: 'Path to rendered site.'
    required: true
    default: '.'
  GITHUB_TOKEN:
    description: 'Github Token.'
outputs:
  preview-url:
    description: 'Preview url.'
    value: ${{ steps.deploy-preview.outputs.preview-url }}
runs:
  using: "composite"
  steps:
    - run: npm install netlify-cli -g
      shell: bash

    - id: deploy-preview
      env:
        NETLIFY_AUTH_TOKEN: ${{ inputs.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ inputs.NETLIFY_SITE_ID }}
      run: netlify deploy --alias ${{ github.ref_name }} --dir ${{ github.workspace }}/${{ inputs.path }}
      shell: bash

    - uses: LouisBrunner/checks-action@v1.1.1
      if: ${{ always() }}
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        name: Netlify-Preview
        conclusion: ${{ job.status }}
        output: |

    - uses: LouisBrunner/checks-action@v1.1.1
      if: ${{ always() }}
      with:
        token: ${{ inputs.GITHUB_TOKEN }}
        name: Netlify-Preview
        conclusion: ${{ job.status }}
        output: |
          {"summary":"Netlify preview created","text_description":""[Link](https://${{ github.ref_name }}--mlr-org.netlify.app)"}
