---
aliases:
  - "/errata.html"
---

# Errata {#sec-appendix-errata}

::: {.content-visible when-format="html"}

{{< include ../../common/_setup.qmd >}}

This appendix lists changes to the online version of this book to chapters included in the first edition.

## 2. Data and Basic Modeling

* Replaced reference to `Param` with `Domain`.

## 3. Evaluation and Benchmarking

* Use `$encapsulate()` method instead of the `$encapsulate` and `$fallback` fields.

## 4. Hyperparameter Optimization

* Renamed `TuningInstanceSingleCrit` to `TuningInstanceBatchSingleCrit`.
* Renamed `TuningInstanceMultiCrit` to `TuningInstanceBatchMultiCrit`.
* Renamed `Tuner` to `TunerBatch`.
* Replaced reference to `Param` with `Domain`.

## 5. Advanced Tuning Methods and Black Box Optimization

* Renamed `TuningInstanceSingleCrit` to `TuningInstanceBatchSingleCrit`.
* Renamed `TuningInstanceMultiCrit` to `TuningInstanceBatchMultiCrit`.
* Renamed `Tuner` to `TunerBatch`.
* Renamed `OptimInstanceSingleCrit` to `OptimInstanceBatchSingleCrit`.
* Renamed `OptimInstanceMultiCrit` to `OptimInstanceBatchMultiCrit`.
* Renamed `Optimizer` to `OptimizerBatch`.
* Replaced `OptimInstanceSingleCrit$new()` with `oi()`.
* Add `oi()` to the table about important functions.
* Use `$encapsulate()` method instead of the `$encapsulate` and `$fallback` fields.
* In example 5.4.4 `lrn("svm")` was tuned instead of `lrn("rpart")`.

## 6. Feature Selection

* Renamed `FSelectInstanceSingleCrit` to `FSelectInstanceBatchSingleCrit`.
* Renamed `FSelectInstanceMultiCrit` to `FSelectInstanceBatchMultiCrit`.
* Renamed `FeatureSelector` to `FeatureSelectorBatch`.
* Add `fsi()` to the table about important functions.

## 8. Non-sequential Pipelines and Tuning

* Use `$encapsulate()` method instead of the `$encapsulate` and `$fallback` fields.

## 10. Advanced Technical Aspects of mlr3

* Use `$encapsulate()` method instead of the `$encapsulate` and `$fallback` fields.

## 11. Large-Scale Benchmarking

* Use `$encapsulate()` method instead of the `$encapsulate` and `$fallback` fields.

## 12. Model Interpretation

* Subset task to row 127 instead of 35 for the local surrogate model.
* Add `as.data.frame()` to "Correctly Interpreting Shapley Values" section.

## 13. Beyond Regression and Classification

* Use `gamma` instead of `gamma.mu` for `lrn("surv.svm")`
* Substitute RCLL with ISBS measure
* Mention `pipeline_responsecompositor()` pipeline for changing predict types
* Use `lrn("surv.xgboost.aft")` instead of `lrn("surv.glmnet")` in "Composition" subsection
