---
aliases:
  - "/tasks.html"
---
# Tasks {#sec-appendix-tasks}

::: {.content-visible when-format="html"}

{{< include ../../common/_setup.qmd >}}

```{r tasks-001, include = FALSE}
library(mlr3verse)
library(mlr3proba)
library(mlr3spatiotempcv)
library(ggplot2)
```

The tasks that are used in this book are listed below including their key features and links to their help pages.

| Type | id | Missings? | Features | Help page |
| ---  | --- | --- | --- | --- |
| Regression | `mtcars` | No | Numeric | `r ref("mlr_tasks_mtcars")` |
| Binary classif (imbalanced) | `german_credit` | No | Mixed | `r ref("mlr_tasks_german_credit")` |
| Multiclass classif | `penguins` | Yes | Mixed | `r ref("mlr_tasks_penguins")` |
| Multiclass classif | `penguins_simple` | No | Numeric | `r ref("mlr_tasks_penguins_simple")` |
| Binary classif | `sonar` | No | Numeric | `r ref("mlr_tasks_sonar")` |
| Binary classif | `pima` | Yes | Numeric | `r ref("mlr_tasks_pima")` |
| Survival | `rats` | No | Mixed | `r ref("mlr3proba::mlr_tasks_rats")` |
| Density | `faithful` | No | Numeric | `r ref("mlr3proba::mlr_tasks_faithful")` |
| Clustering | `usarrests` | No | Numeric | `r ref("mlr3cluster::mlr_tasks_usarrests")` |
| Spatiotemporal | `ecuador` | No | Numeric | `r ref("mlr3spatiotempcv::mlr_tasks_ecuador")` |

:::
