# Special Tasks {#special-tasks}

The section on special tasks explores the different functions of mlr3, when dealing with peculiar data sets that require further modifications to undertake sensible analysis.

This chapter will illustrate on how to deal with the following topics:

##Survival Analysis 

Survival analysis is used to monitor the time until a specific event occurs.
This specific event could be e.g. death, transmission of a disease marriage or divorce.
Two considerations are important here, namely on the one hand whether the event occurred within the frame of the given data and on the other hand how much time it took until the event occurred.
Moreover one cannot use a ordinary regression analysis when dealing with survival analysis data sets.
First of all, survival data contains solely positive values and therefore needs to be transformed to avoid biases.
Secondly, ordinary regression analysis cannot deal with censored observations accordingly.
Censored observations are observations in which the event of interest has not occurred, yet.
Survival analysis allows the user to handle censored data with limited time frames that sometimes do not entail the event of interest.
Note that survival analysis accounts for both censored and uncensored observations while adjusting respective model parameters. 

In summary, this sub-chapter will illustrate how to conduct survival data analysis in an optimal manner using mlr3.

##Spatial Data Analysis

Spatial data observations entail reference information.
Treating spatial data using non-spatial data methods could lead to over-optimistic treatment.

Therefore, this sub-chapter will illustrate how to handle spatial data accordingly.

##Ordinal Data Analysis

Coming soon!

##Multilabel Data Analysis

Multilabel data analysis deals with data sets that contain multivariate data with an ordering on the dimension.
Numerous target labels are attributed to a single observation.
Mulitlabel data consists of waves over a specific length.
Firstly, multilabel data allows one to use modified algorithms, to accommodate data specific characteristics.

This sub-chapter will introduce two approaches namely the problem transformation method and the algorithm adaption method.

##Cost Sensitive Classification 

The last sub-chapter of this chapter deals with how implement cost sensitivity analysis.
In regular classification the aim is to minimize the misclassification rate and thus all types of misclassification errors are deemed equally severe.
A more general setting is cost-sensitive classification where the costs caused by different kinds of errors are not assumed to be equal and the objective is to minimize the expected costs.
First of all, this sub-chapter provides guidance on how to implement a first model.
Following the implementation of the first model, there are instructions on how to modify cost sensitivity measures.
Subsequently, thresholding and threshold tuning is explained.

