---
title: "`latex-math` Macros"
output: pdf_document
header-includes:
   - \usepackage{mathtools}
   - \usepackage{bm}
   - \usepackage{siunitx}
   - \usepackage{dsfont}
   - \usepackage{xspace}
   - \usepackage{longtable}
   - \input{basic-ml.tex}
   - \input{basic-math.tex}
   - \input{ml-bagging.tex}
   - \input{ml-boosting.tex}
   - \input{ml-gp.tex}
   - \input{ml-mbo.tex}
   - \input{ml-nn.tex}
   - \input{ml-svm.tex}
   - \input{ml-trees.tex}
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(purrr)
library(xtable)
```

<!-- Run this file with rmarkdown::render() to recreate the tables.  -->

Latex macros like `\frac{#1}{#2}` with arguments are displayed as $\frac{\#1}{\#2}$.


```{r get-macros, echo = FALSE, warning = FALSE}
# escape the "#"-sign for latex macros with arguments
sanitize_command <- function(command) {
  paste0("$", 
         stringr::str_replace_all(
           command, 
           pattern = "#([1-9])",
           replacement = "{\\\\#\\1}"), 
         "$")
}
get_command <- function(line) {
  #see https://www.regular-expressions.info/recurse.html#balanced
  command <- regmatches(line, 
                        gregexpr("\\{(?>[^{}]|(?R))*\\}", 
                                 line, perl = TRUE)
                        )[[1]]
  if (length(command) != 2) return(NULL)
  command[3] <- stringr::str_match(line, 
                          pattern = "\\}\\s*%\\s*(.*)$")[-1]
  names(command) <- c("Macro", "Notation", "Comment")
  command[1] <- substr(command[1], 2, nchar(command[1])-1)
  if (grepl("IGNORE_NOTATION", command[3])) {
    command[2] <- ""
  }
  command[1] <- paste0("\\verb!", command[1], "!")
  command[2] <- sanitize_command(command[2])
  command[3] <- xtable::sanitize(command[3])
  command
}

texfiles <- list.files(pattern = "\\.tex$")
texfiles <- setdiff(texfiles, "latex-math.tex") # avoid itself
macros <- texfiles %>% 
  map(~ readLines(.)) %>% 
  map_depth(.depth = 2, ~ get_command(.)) %>% 
  map(~ discard(., .p = is.null) %>% 
        do.call(rbind, .)) 
names(macros) <- texfiles
```

```{r print-macros, results='asis', echo = FALSE}
for (i in seq_along(macros)) {
  cat("\\section{",  names(macros)[i], "} ")
  null <- print(xtable(macros[[i]]), 
                sanitize.text.function = I, 
                include.rownames = FALSE, 
                floating = FALSE,
                tabular.environment = "longtable", 
                comment = FALSE)
  cat("\\newpage")
}
```
