# Introduction and Overview

The `r mlr_pkg("mlr3")` package and ecosystem provides a generic, object-oriented, and extensible framework for classification, regression, survival analysis, and other machine learning tasks for the R language.
It does not implement any learners itself, but provides a unified interface to many existing learners in R.
This unified interface allows to provide functionality to extend and combine existing learners, intelligently select and tune the most appropriate technique for a task, and perform large-scale comparisons that enable meta-learning.
Examples of this advanced functionality include hyperparameter tuning, feature selection, and ensemble construction. Parallelization of many operations is natively supported.

**Target Audience**

`r mlr_pkg("mlr3")` provides a domain-specific language for machine learning in R.
We target both **practitioners** who want to quickly apply machine learning algorithms and **researchers** who want to implement, benchmark, and compare their new methods in a structured environment.
The package is a complete rewrite of an earlier version of `r mlr_pkg("mlr")` that leverages many years of experience to provide a state-of-the-art system that is easy to use and extend.
It is intended for users who have basic knowledge in machine learning and R and who are interested in complex projects and advanced functionality rather than one-liners for one specific thing.

**Why a Rewrite?**

`r mlr_pkg("mlr")` was first released to CRAN in 2013, with the core design and architecture dating back much further.
Over time, the addition of many features has led to a considerably more complex design that made it harder to build, maintain, and extend than we had hoped for.
Further, the R ecosystem was not as far developed at the time, for example `r cran_pkg("data.table")` did not exist.
Including such helpful packages makes `r mlr_pkg("mlr3")` easier to maintain, to use, and more performant, but also resulted in non-trivial API changes that would have been hard to implement and support in `r mlr_pkg("mlr")`.
With hindsight, we saw that some of the design and architecture changes in `r mlr_pkg("mlr")` made it difficult to support new features, in particular with respect to pipelines.
In 2018, we decided to start working on the reimplementation, and in July 2019 we released the first version of `r mlr_pkg("mlr3")` to CRAN.

**Design Principles**

We follow the general design principles below in the implementation of the `r mlr_pkg("mlr3")` package and ecosystem.

* Backend over frontend.
  Most packages of the `r mlr_pkg("mlr3")` ecosystem focus on processing and transforming data, applying machine learning algorithms, and computing results.
  We do not provide graphical user interfaces (GUIs) and visualizations of data and results is provided in extra packages.
* Embrace [R6](https://cran.r-project.org/package=R6), clean object-oriented design, object state-changes, and reference semantics.
* Embrace [`data.table`](https://cran.r-project.org/package=data.table) for fast and convenient data frame computations.
* Unify container and result classes as much as possible and provide result data in `data.table`s.
    This considerably simplifies the API and allows easy selection and aggregation operations.
    We combine `data.table` and `R6` to place references to non-atomic and compound objects in tables and make heavy use of list columns.
* Be light on dependencies.
  One of the main maintenance burdens for `r mlr_pkg("mlr")` was to keep up with changing learner interfaces and behaviour of the many packages it depended on.
  We require far fewer packages in `r mlr_pkg("mlr3")` to make installation and maintenance easier.

`r mlr_pkg("mlr3")` requires the following packages:

- [`backports`](https://cran.r-project.org/package=backports): Ensures backward compatibility with older R releases.
    Developed by members of the `r mlr_pkg("mlr3")` team.
    No additional dependencies.
- [`checkmate`](https://cran.r-project.org/package=checkmate): Fast argument checks.
    Developed by members of the `r mlr_pkg("mlr3")` team.
    No additional dependencies.
- [`mlr3misc`](https://github.com/mlr-org/mlr3misc) Miscellaneous functions used in multiple `r mlr_pkg("mlr3")` [extension packages](https://github.com/mlr-org/mlr3/wiki/Extension-Packages).
    Developed by the `r mlr_pkg("mlr3")` team.
    No additional dependencies.
- [`paradox`](https://github.com/mlr-org/paradox): Description for parameters and parameter sets.
    Developed by the `r mlr_pkg("mlr3")` team.
    No additional dependencies.
- [`R6`](https://cran.r-project.org/package=R6): Reference class objects.
    No additional dependencies.
- [`data.table`](https://cran.r-project.org/package=data.table): Extension of R's `data.frame`.
    No additional dependencies.
- [`digest`](https://cran.r-project.org/package=digest): Hash digests.
    No additional dependencies.
- [`lgr`](https://github.com/s-fleck/lgr): Logging.
    No additional dependencies.
- [`Metrics`](https://cran.r-project.org/package=Metrics): Performance measures.
    No additional dependencies.
- [`mlbench`](https://cran.r-project.org/package=mlbench): Collection of machine learning data sets.
    No additional dependencies.

`r mlr_pkg("mlr3")` provides additional functionality through extra packages:

- For parallelization, `r mlr_pkg("mlr3")` utilizes the [`future`](https://cran.r-project.org/package=future) and [`future.apply`](https://cran.r-project.org/package=future.apply) packages.
- To capture output, warnings, and exceptions, [`evaluate`](https://cran.r-project.org/package=evaluate) and [`callr`](https://cran.r-project.org/package=callr) can be used.
