# Introduction and Overview

The `r mlr_pkg("mlr3")` package and ecosystem provides a generic, object-oriented, and extensible framework for [classification](#tasks), [regression](#tasks), [survival analysis](#survival), and other machine learning tasks for the R language.
It does not implement any [learners](#learners) itself, but provides a unified interface to many existing learners in R.
This unified interface allows to provide functionality to extend and combine existing [learners](#learners), intelligently select and tune the most appropriate technique for a [task](#tasks), and perform large-scale comparisons that enable meta-learning.
Examples of this advanced functionality include [hyperparameter tuning](#tuning), [feature selection](#fs), and [ensemble construction](#fs-ensemble). [Parallelization](#parallelization) of many operations is natively supported.

**Target Audience**

`r mlr_pkg("mlr3")` provides a domain-specific language for machine learning in R.
We target both **practitioners** who want to quickly apply machine learning algorithms and **researchers** who want to implement, benchmark, and compare their new methods in a structured environment.
The package is a complete rewrite of an earlier version of `r mlr_pkg("mlr")` that leverages many years of experience to provide a state-of-the-art system that is easy to use and extend.
It is intended for users who have basic knowledge in machine learning and R and who are interested in complex projects and advanced functionality rather than one-liners for one specific thing.

**Why a Rewrite?**

`r mlr_pkg("mlr")` was first released to CRAN in 2013, with the core design and architecture dating back much further.
Over time, the addition of many features has led to a considerably more complex design that made it harder to build, maintain, and extend than we had hoped for.
With hindsight, we saw that some of the design and architecture changes in `r mlr_pkg("mlr")` made it difficult to support new features, in particular with respect to pipelines.
Furthermore, the R ecosystem as well as helpful packages such as `r cran_pkg("data.table")` have undergone major changes in the meantime.
It would have been nearly impossible to integrate all these changes into the original design of `r mlr_pkg("mlr")`.
Instead, we decided to start working on a reimplementation in 2018, which resulted in the first release of `r mlr_pkg("mlr3")` on CRAN in July 2019.
The new design and the integration of further and newly developed R packages (**R6**, **future**, **data.table**) makes `r mlr_pkg("mlr3")` much easier to maintain and use, and more performant compared to `r mlr_pkg("mlr")`.

**Design Principles**

We follow the general design principles below in the implementation of the `r mlr_pkg("mlr3")` package and ecosystem.

* Backend over frontend.
  Most packages of the `r mlr_pkg("mlr3")` ecosystem focus on processing and transforming data, applying machine learning algorithms, and computing results.
  We do not provide graphical user interfaces (GUIs) and visualizations of data and results is provided in extra packages.
* Embrace `r cran_pkg("R6")` for a clean object-oriented design, object state-changes, and reference semantics.
* Embrace `r cran_pkg("data.table")` for fast and convenient data frame computations.
* Unify container and result classes as much as possible and provide result data in `data.table`s.
    This considerably simplifies the API and allows easy selection and "split-apply-combine" (aggregation) operations.
    We combine `data.table` and `R6` to place references to non-atomic and compound objects in tables and make heavy use of list columns.
* Be light on dependencies.
  One of the main maintenance burdens for `r mlr_pkg("mlr")` was to keep up with changing learner interfaces and behavior of the many packages it depended on.
  We require far fewer packages in `r mlr_pkg("mlr3")` to make installation and maintenance easier.

`r mlr_pkg("mlr3")` requires the following packages:

  * `r cran_pkg("backports")`:
    Ensures backward compatibility with older R releases. Developed by members of the `mlr` team.
    No recursive dependencies.
  * `r cran_pkg("checkmate")`:
    Fast argument checks. Developed by members of the `mlr` team.
    No extra recursive dependencies.
  * `r cran_pkg("mlr3misc")`:
    Miscellaneous functions used in multiple mlr3 [extension packages](https://github.com/mlr-org/mlr3/wiki/Extension-Packages).
    Developed by the `mlr` team.
    No extra recursive dependencies.
  * `r cran_pkg("paradox")`:
    Descriptions for parameters and parameter sets. Developed by the `mlr` team.
    No extra recursive dependencies.
  * `r cran_pkg("R6")`:
    Reference class objects.
    No recursive dependencies.
  * `r cran_pkg("data.table")`:
    Extension of R's `data.frame`.
    No recursive dependencies.
  * `r cran_pkg("digest")`:
    Hash digests.
    No recursive dependencies.
  * `r cran_pkg("uuid")`:
    Create unique string identifiers.
    No recursive dependencies.
  * `r cran_pkg("lgr")`:
    Logging facility.
    No extra recursive dependencies.
  * `r cran_pkg("mlr3measures")`:
    Performance measures.
    No extra recursive dependencies.
  * `r cran_pkg("mlbench")`:
    A collection of machine learning data sets.
    No dependencies.

`r mlr_pkg("mlr3")` provides additional functionality through extra packages:

* For [parallelization](#parallelization), `r mlr_pkg("mlr3")` utilizes the `r cran_pkg("future")` and `r cran_pkg("future.apply")` packages.
* To capture output, warnings and exceptions, `r cran_pkg("evaluate")` and `r cran_pkg("callr")` can be used.
