## Parallelization {#parallelization}

Parallelization refers to the process of running multiple jobs in parallel, simultaneously.
This process allows for significant savings in computing power.

`r mlr_pkg("mlr3")` uses the `r cran_pkg("future")` backends for parallelization.
Make sure you have installed the required packages `r cran_pkg("future")` and `r cran_pkg("future.apply")`:

`r mlr_pkg("mlr3")` is capable of parallelizing a variety of different scenarios.
One of the most used cases is to parallelize the `r ref("Resampling")` iterations.
See [Section Resampling](#resampling) for a detailed introduction to resampling.

In the following section, we will use the _spam_ task and a simple classification tree (`"classif.rpart"`) to showcase parallelization.
We use the `r cran_pkg("future")` package to parallelize the resampling by selecting a backend via the function `r ref("future::plan()")`.
We use the `r ref("future::multiprocess")` backend here which uses forks (c.f. `r ref("parallel::mcparallel()")`) on UNIX based systems and a `r ref("parallel::makePSockCluster()", "socket cluster")` on Windows or if running in [RStudio](https://rstudio.com/):


```{r 05-technical-parallelization-001, eval = FALSE}
future::plan("multiprocess")

task = tsk("spam")
learner = lrn("classif.rpart")
resampling = rsmp("subsampling")

time = Sys.time()
resample(task, learner, resampling)
Sys.time() - time
```
By default all CPUs of your machine are used unless you specify argument `workers` in `r ref("future::plan()")`.

On most systems you should see a decrease in the reported elapsed time.
On some systems (e.g. Windows), the overhead for parallelization is quite large though.
Therefore, it is advised to only enable parallelization for resamplings where each iteration runs at least 10 seconds.

**Choosing the parallelization level**

If you are transitioning from `r cran_pkg("mlr")`, you might be used to selecting different parallelization levels, e.g. for resampling, benchmarking or tuning.
In `r mlr_pkg("mlr3")` this is no longer required.
All kind of events are rolled out on the same level.
Therefore, there is no need to decide whether you want to parallelize the tuning OR the resampling.

In `r mlr_pkg("mlr3")` this is no longer required.
All kind of events are rolled out on the same level - there is no need to decide whether you want to parallelize the tuning OR the resampling.

Just lean back and let the machine do the work :-)

