## Integrated Filter Methods {#list-filters}

### Standalone filter methods {#fs-filter-list}

```{r 98-appendix-003, echo=FALSE, eval = T}
library("mlr3filters")
library("magrittr")
as.data.frame(data.table::as.data.table(mlr_filters)) %>%
  dplyr::mutate(task_type = as.character(task_type)) %>%
  dplyr::mutate(feature_types = as.character(feature_types)) %>%

  dplyr::mutate(task_type = dplyr::recode(task_type, 'c("classif", "regr")' = 'Classif & Regr')) %>%
  dplyr::mutate(task_type = dplyr::recode(task_type,
    'classif' = 'Classif')) %>%
  dplyr::mutate(task_type = dplyr::recode(task_type,
    'regr' = 'Regr')) %>%
  dplyr::mutate(feature_types = dplyr::recode(feature_types,
    'c(\"integer\", \"numeric\", \"factor\", \"ordered\")' = 'Integer, Numeric, Factor, Ordered')) %>%
  dplyr::mutate(feature_types = dplyr::recode(feature_types,
    'c(\"integer\", \"numeric\")' = 'Integer, Numeric')) %>%

  dplyr::arrange(desc(task_type)) %>%
  dplyr::mutate(packages = kableExtra::cell_spec(
    packages,  italic = TRUE)) %>%
  dplyr::rename(Package = packages, Features = feature_types,
    Task = task_type, Name = key) %>%
  kableExtra::kable(escape = T) %>%
  kableExtra::kable_styling(bootstrap_options = c("striped", "hover",
    "condensed", "responsive"),
    font_size = 12)
```

### Algorithms With Embedded Filter Methods {#fs-filter-embedded-list}

```{r 98-appendix-004, echo = FALSE}
data.table::as.data.table(mlr_learners)[mlr3misc::map_lgl(properties, is.element, el = "importance"), key]
```

