# Appendix {#appendix}

## Integrated Learners {#list-learners}

```{r 98-appendix-001, echo=FALSE}
translate_types = function(x) {
  r_types = mlr_reflections$task_feature_types
  p_types = names(mlr_reflections$task_feature_types)
  factor(mlr3misc::map_values(x, r_types, p_types), levels = p_types)
}

requireNamespace("mlr3learners")
requireNamespace("mlr3proba")
d = as.data.table(mlr_learners)

# Display the feature types in title case.
d$feature_types = vapply(d$feature_types, function(x) {
  paste0(translate_types(x), collapse = ", ")
}, character(1))

if (knitr::is_html_output()) {
  # Display package name, or None, if no package is required.
  d$packages = mlr3misc::map_chr(d$packages, function(x) {
    ifelse(length(x) == 0, "", paste0(sapply(sort(x), cran_pkg), collapse = ", "))
  })
}

# Display properties in title case. Also remove _ and replace it with space.
d$properties = mlr3misc::map_chr(d$properties, function(x) {
  paste0(tools::toTitleCase(gsub("_", " ", x)), collapse = ", ")
})

d$predict_types = mlr3misc::map_chr(d$predict_types, function(x) {
  paste0(x, collapse = ", ")
})

colnames(d) = c("Id", "Feature Types", "Required packages", "Properties", "Predict Types")

if (knitr::is_latex_output()) {
  colnames(d) = c("Id", "Feature Types", "Required packages", "Properties", "Predict Types")
  flextable(d) %>%
    width(j = 1, width = 1) %>%
    width(j = 2, width = 2) %>%
    width(j = 3, width = 0.5) %>%
    width(j = 4, width = 3) %>%
    width(j = 5, width = 2) %>%
    height_all(.22) %>%
    border_inner_h(border = officer::fp_border(color = "gray")) %>%
    fontsize(size = 11, part = "all")
} else if (knitr::is_html_output()) {
  knitr::kable(d, col.names = c("Id", "Feature Types", "Required packages", "Properties", "Predict Types"))
}
```

## Integrated Performance Measures {#list-measures}

Also see the [overview on the website](https://mlr3measures.mlr-org.com/reference/) of `r mlr_pkg("mlr3measures")`.

```{r 98-appendix-002, echo=FALSE}
library("data.table")
d = as.data.table(mlr_measures)

if (knitr::is_html_output()) {
  d$packages = mlr3misc::map_chr(d$packages, function(x) {
    ifelse(length(x) == 0, "", paste0(sapply(sort(x), cran_pkg), collapse = ", "))
  })
}

d$task_properties = mlr3misc::map_chr(d$task_properties, paste0, collapse = ", ")

setcolorder(d, c("key", "task_type", "packages", "task_properties", "predict_type"))

if (knitr::is_latex_output()) {
  colnames(d) = c("Id", "Task Type", "Required packages", "Task Properties", "Predict Type")
  flextable(d) %>%
    width(j = 1, width = 1) %>%
    width(j = 2, width = 1) %>%
    width(j = 3, width = 1.5) %>%
    width(j = 4, width = 1) %>%
    width(j = 5, width = 1) %>%
    height_all(.13) %>%
    border_inner_h(border = officer::fp_border(color = "gray")) %>%
    fontsize(size = 7, part = "all")
} else if (knitr::is_html_output()) {
  knitr::kable(d, col.names = c("Id", "Task Type", "Required packages", "Task Properties", "Predict Type"))
}
```

## Integrated Filter Methods {#list-filters}

### Standalone filter methods {#fs-filter-list}

```{r 98-appendix-003, echo=FALSE}
library(mlr3filters)
library(magrittr)

translate_types = function(x) {
  r_types = mlr_reflections$task_feature_types
  p_types = names(mlr_reflections$task_feature_types)
  factor(mlr3misc::map_values(x, r_types, p_types), levels = p_types)
}

d = as.data.table(mlr_filters)

d$feature_types = vapply(d$feature_types, function(x) {
  paste0(translate_types(x), collapse = ", ")
}, character(1))

d$param_set = NULL
colnames(d) = c("Id", "Task", "Task Properties", "Features", "Package")

if (knitr::is_html_output()) {
  # Display package name, or None, if no package is required.
  d$Package = mlr3misc::map_chr(d$Package, function(x) {
    ifelse(length(x) == 0, "", paste0(sapply(sort(x), cran_pkg), collapse = ", "))
  })
}

if (knitr::is_latex_output()) {
  flextable(d) %>%
    width(j = 1, width = 1.5) %>%
    width(j = 2, width = 1) %>%
    width(j = 3, width = 1.5) %>%
    width(j = 5, width = 1) %>%
    width(j = 4, width = 2) %>%
    width(j = 5, width = 1) %>%
    height_all(.22) %>%
    border_inner_h(border = officer::fp_border(color = "gray")) %>%
    fontsize(size = 11, part = "all")
} else if (knitr::is_html_output()) {
  knitr::kable(d)
}
```

### Algorithms With Embedded Filter Methods {#fs-filter-embedded-list}

```{r 98-appendix-004, echo = FALSE}
as.data.table(mlr_learners)[mlr3misc::map_lgl(properties, is.element, el = "importance"), key]
```
