---
title: "mlr3 manual"
author: "The mlr-org Team"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
documentclass: book
bibliography: book.bib
biblio-style: apalike
link-citations: yes
monofontoptions: "Scale=0.7"
monofont: "Source Code Pro"
colorlinks: yes
url: 'https\://mlr3book.mlr-org.com'
github-repo: mlr-org/mlr3book
always_allow_html: yes
---

```{r index-001, include = FALSE, comment="", results="asis"}
requireNamespace("mlr3")
library("mlr3book")

options(
  width = 80,
  digits = 4,
  knitr.graphics.auto_pdf = TRUE,
  crayon.enabled = TRUE
)

if(!knitr:::is_html_output())
{
  options("width"=56)
  knitr::opts_chunk$set(tidy.opts=list(width.cutoff=56, indent = 2), 
    tidy = TRUE)
  knitr::opts_chunk$set(fig.pos = 'H')
}

old.hooks = fansi::set_knit_hooks(knitr::knit_hooks)
knitr::opts_chunk$set(collapse = TRUE, cache = FALSE)
lgr::get_logger("mlr3")$set_threshold("warn")
requireNamespace("kableExtra")
library("R6")
```

# Prerequisites

To run all code examples in this book successfully, install the `r gh_pkg("mlr-org/mlr3book")` package using the `r cran_pkg("remotes")` package:

```{r index-002, eval = FALSE}
remotes::install_github("mlr-org/mlr3book", dependencies = TRUE)
```

After the installation, load the `mlr3` package and you are good to go:

```{r index-003, eval = FALSE}
library(mlr3)
```
